### ISSUE TITLE
Keys directory is not generated

### ISSUE THREAD

**Issue by claw68** [SAP/gigya-php-sdk#9]
The fix for src/keys/ directory creation is under v3.0.1 but the composer/packagist version is stuck on v3.0

https://packagist.org/packages/gigya/php-sdk

Please update the composer version to address the file not found issue when using JWTUtils::validateSignature

**Comment by Ynhockey** [comment]
Hi claw68,

I have fixed the version numbering, and with the latest (3.0.2) the keys directory should be generated correctly.

Thanks for pointing it out.
